services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    container_name: dash-buchinger-app
    restart: unless-stopped
    networks:
      - shared-proxy
    environment:
      - PYTHONUNBUFFERED=1
networks:
  shared-proxy:
    external: true
